### ISSUE TITLE
Issue when changing all the outputs at once

### ISSUE THREAD

**Issue by tombsy** [piface/pifacedigital-scratch-handler#1]
Hi,

Have found your handler really useful, many thanks, however I have found when setting all the outputs at the same time in scratch then only the first 4 outputs would be set.

By amending the BUFFER_SIZE at the top to 175  ie (BUFFER_SIZE = 175) then this resolves the issue as I think the if..elif..else logic at the end was putting anything over the buffer size into "received something".

I dont think the increased BUFFER_SIZE has a detrimental effect to the running of the code

I'm afraid I dont understand the branching code option in github as a new user so hope you find this comment useful!

thanks again

**Comment by tompreston** [comment]
Hi, I've updated this now, thanks.

Also, I've noticed that I've let this program get out of date so I've updated it to use the latest changes to pifacedigitalio and pifacecommon. So before updating this you'll have to update them (By the way, I'm working on making everything slightly easier to install and update).

Any problems let me know. :-)

**Comment by tombsy** [comment]
cheers - will give it a whirl when I get 5 mins (or 105 mins with my current ability!)
