### ISSUE TITLE
Error on install, upgrade, removal

### ISSUE THREAD

**Issue by ghost** [piface/pifacedigital-scratch-handler#2]
I can not update my Pi because of this error... 

Do you want to continue [Y/n]? y
(Reading database ... 100409 files and directories currently installed.)
Preparing to replace python3-pifacedigital-scratch-handler 2.0.2-1 (using .../python3-pifacedigital-scratch-handler_2.0.3-1_all.deb) ...
Unpacking replacement python3-pifacedigital-scratch-handler ...
rm: cannot remove `/home/pi/Desktop/pifacedigital-scratch-handler.desktop': No such file or directory
dpkg: warning: subprocess old post-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
rm: cannot remove`/home/pi/Desktop/pifacedigital-scratch-handler.desktop': No such file or directory
dpkg: error processing /var/cache/apt/archives/python3-pifacedigital-scratch-handler_2.0.3-1_all.deb (--unpack):
 subprocess new post-removal script returned error exit status 1
rm: cannot remove `/home/pi/Desktop/pifacedigital-scratch-handler.desktop': No such file or directory
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/python3-pifacedigital-scratch-handler_2.0.3-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by tompreston** [comment]
The latest update removes the auto-installation of the desktop icon however I forgot to remove the auto-remove bit. I've submitted a patch to Raspbian. I'll let you know when they've updated it.

**Comment by ghost** [comment]
Thanks for your quick reply! I will try it later again.

**Comment by tompreston** [comment]
Fixed. I've submitted the new .deb to Raspbian. You can get it manually from here: https://github.com/piface/pifacedigital-scratch-handler/releases

Thanks for bug reporting!
